name: build image and push to DockerHub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3

    - name: set date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Show date
      run: echo ${{ steps.date.outputs.date }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0
      with:
        platforms: all

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2.3.0

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3.3.0
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./
        file: ./Dockerfile.${{ matrix.version }}
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: ${{ github.event_name != 'pull_request' }}
        pull: true
        no-cache: true
        tags: |
          xr09/python-requests:${{ matrix.version }}
          xr09/python-requests:${{ matrix.version }}-${{ steps.date.outputs.date }}

    - name: Push latest
      id: docker_build_latest
      uses: docker/build-push-action@v3.3.0
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./
        file: ./Dockerfile.3.11
        platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
        push: ${{ github.event_name != 'pull_request' }}
        pull: true
        cache-from: type=registry,ref=xr09/python-requests:latest
        cache-to: type=inline
        tags: |
          xr09/python-requests:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
